/** Frozen-source four-resource check only; no browser/native/UI acceptance or source edits. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{createRequire}from'node:module';import{pathToFileURL}from'node:url';
const args=Object.fromEntries(process.argv.slice(2).reduce((out,value,index,array)=>{if(index%2===0)out.push([value,array[index+1]]);return out;},[]));
const root=path.resolve(args['--source-root']),work=path.resolve(args['--work-root']),receiptPath=path.resolve(args['--source-key-receipt']),recipe=JSON.parse(fs.readFileSync(args['--recipe'])),locales=['en','zh-Hant','zh-Hans','ja'];assert.deepEqual(recipe.supported_locales,locales);
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),sourceReceipt=JSON.parse(fs.readFileSync(receiptPath));
const depRequire=createRequire(path.join(root,'packages/ui-locale/package.json'));const i18nextModule=pathToFileURL(depRequire.resolve('i18next').replace('/dist/cjs/','/dist/esm/')).href;const results={};
for(const[app,prefix]of[['litellm','ui/litellm-dashboard'],['llama-swap','ui']]){
 const domain=sourceReceipt.apps?.[app]??sourceReceipt,keys=domain.usedKeys;assert.ok(Array.isArray(keys)&&keys.length);assert.equal(new Set(keys).size,keys.length);assert.ok(keys.every(key=>typeof key==='string'&&key));assert.equal(sourceReceipt.sourceTrees?.[app],recipe.apps[app].source_tree_sha256);

 const base=path.join(work,app,prefix,'src/liliuxflow'),catalogs={},catalogHashes={};
 assert.deepEqual(recipe.apps[app].runtime_catalogs.map(x=>x.locale),locales);
 for(const item of recipe.apps[app].runtime_catalogs){const target=item.target??prefix+'/'+item.path;assert.ok(target.startsWith(prefix+'/')&&!target.split('/').includes('..'));const extra=recipe.apps[app].extra_files.find(file=>file.target===target&&file.sha256===item.sha256);assert.ok(extra);if(item.target)assert.equal(extra.source,item.path);const bytes=fs.readFileSync(path.join(work,app,target));assert.equal(sha(bytes),item.sha256);catalogs[item.locale]=JSON.parse(bytes);catalogHashes[item.locale]=item.sha256;}
 const coreBytes=fs.readFileSync(path.join(base,'core.mjs'));const coreText=coreBytes.toString();assert.ok(coreText.includes("from 'i18next'"));const importOnlyRemap=coreText.replace("from 'i18next'",'from '+JSON.stringify(i18nextModule));const core=await import('data:text/javascript;base64,'+Buffer.from(importOnlyRemap).toString('base64'));assert.deepEqual([...core.LOCALES],locales);const allKeys=core.validateCatalogs(catalogs);const missing={};
 for(const locale of locales){missing[locale]=keys.filter(key=>typeof catalogs[locale][key]!=='string'||!catalogs[locale][key].trim());assert.equal(missing[locale].length,0);}
 const tags=text=>[...text.matchAll(/<([A-Za-z][A-Za-z0-9]*)\/>/g)].map(x=>x[1]).sort();let richKeys=0;for(const key of allKeys){const expected=tags(catalogs.en[key]);if(expected.length){richKeys++;for(const locale of locales)assert.deepEqual(tags(catalogs[locale][key]),expected);}}
 const runtime=core.createLocaleRuntime(structuredClone(catalogs),'en',{declaredKeys:keys});assert.equal(runtime.options.fallbackLng,false);assert.equal(core.mapBrowserLocale('en-US'),'en');assert.equal(core.mapBrowserLocale('en-GB'),'en');assert.equal(core.initialLocale('liliuxflow_locale=en',['zh-TW']),'en');assert.equal(core.initialLocale('liliuxflow_locale=zh-Hant',['en-US']),'zh-Hant');
 for(const key of keys)assert.equal(runtime.getResource('en','translation',key),catalogs.en[key]);
 const different=keys.find(key=>catalogs.en[key]!==catalogs['zh-Hant'][key]);assert.ok(different);const bad=structuredClone(catalogs);delete bad.en[different];assert.throws(()=>core.validateCatalogs(bad));const negativeRuntime=core.createLocaleRuntime(structuredClone(catalogs),'en',{declaredKeys:keys});delete negativeRuntime.services.resourceStore.data.en.translation[different];assert.equal(negativeRuntime.getResource('en','translation',different),undefined);assert.notEqual(negativeRuntime.t(different),catalogs['zh-Hant'][different]);assert.ok(core.getLocaleDiagnostics(negativeRuntime).unresolvedCount>0);
 const declared=JSON.parse(fs.readFileSync(path.join(base,'source-message-keys.json'))),diagnosticOnly=declared.filter(key=>!Object.hasOwn(catalogs.en,key));
 results[app]={sourceKeyScope:domain.scope??sourceReceipt.scope,catalogHashes,catalogKeys:allKeys.length,sourceUsedKeys:keys.length,directMissing:missing,richSelfClosingSlotKeys:richKeys,coreOriginalSHA256:sha(coreBytes),harnessOnlyBareImportResolverRemapped:true,fallbackLng:false,ENDirectComplete:true,deliberatelyMissingENKeyRejected:true,noHantFallbackOnMissingEN:true,ENBrowserNormalizationAndSavedPreferencesPreserved:true,declaredMissingDiagnosticIDs:diagnosticOnly.length,declaredDomain:'diagnostic inventory, not current source-used coverage'};
}
const result={status:'PASS_FROZEN_SOURCE_FOUR_RUNTIME_RESOURCES_CPU_ONLY',recipeSHA256:sha(fs.readFileSync(args['--recipe'])),sourceKeyReceiptSHA256:sha(fs.readFileSync(receiptPath)),sourceKeyScope:sourceReceipt.scope,apps:results,selectorsLoginDOMBrowser:'OWNER_SEPARATE_TESTS_NOT_RERUN',sourceHumanConsumerCoverage:'NOT_PROVEN_BY_CATALOG_COUNT',uiAccepted:false,nativeArchiveLiveModel:'NOT_RUN'};fs.writeFileSync(args['--output'],JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,apps:Object.fromEntries(Object.entries(results).map(([name,value])=>[name,{catalogKeys:value.catalogKeys,sourceUsedKeys:value.sourceUsedKeys,directMissing:value.directMissing,ENNoHantFallback:true,declaredDiagnosticOnlyMissing:value.declaredMissingDiagnosticIDs}])),uiAccepted:false}));
